# Generated by Django 3.1.6 on 2021-03-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
